# Generated by Django 4.1.3 on 2022-12-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(default=None, max_length=100)),
                ('staff_number', models.IntegerField()),
            ],
        ),
    ]
